languageCode = "en-us"
title = "@jeqo"
baseurl = "https://jeqo.github.io/"

theme = "jeqo-theme"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
MetaDataFormat = "yaml"
PygmentsStyle = "default"

disqusShortname = "jeqoblog"
googleAnalytics = "UA-49047812-3"

[author]
    name = "Jorge Quilcate Otoya"

[params]
    description = "back-end development, integration, devops, etc."

[taxonomies]
    tag = "tags"
    category = "categories"

[[menu.main]]
    name = "GitHub"
    pre = ""
    weight = -100
    url = "https://github.com/jeqo/"
[[menu.main]]
    name = "Twitter"
    pre = ""
    weight = -90
    url = "https://twitter.com/jeqo89"
[[menu.main]]
    name = "RSS"
    pre = ""
    weight = -80
    url = "index.xml"

[Languages]
    [Languages.en]
        weight = 1

    [Languages.es]
        baseurl = "https://jeqo.github.io/es"
        weight = 2
        description = "desarrollo de 'back-end', integración, 'devops', etc."
