languageCode = "en-us"
title = "@jeqo"
baseurl = "https://jeqo.github.io/"

theme = "jeqo-theme"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
MetaDataFormat = "yaml"

disqusShorname = "jeqo"

[params]
    copyright = "&copy Copyright 2017. Jorge Quilcate."
    description = "back-end development, integration, devops, etc."

[taxonomies]
    tag = "tags"
    category = "categories"

[[menu.main]]
    name = "Twitter"
    pre = ""
    weight = -100
    url = "http://www.twitter.com/jeqo89"
[[menu.main]]
    name = "RSS"
    pre = ""
    weight = -90
    url = "index.xml"

[Languages]
[Languages.en]
    weight = 1

[Languages.es]
    baseurl = "https://jeqo.github.io/es"
    weight = 2
    description = "desarrollo de 'back-end', integración, 'devops', etc."