languageCode = "en-us"
title = "@jeqo"
baseurl = "https://jeqo.github.io/"

theme = "jeqo-theme-2"

MetaDataFormat = "yaml"
PygmentsCodeFences = true
PygmentsStyle = "colorful"

# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright @jeqo"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "jeqo89"
  #facebook = "Your Facebook username"
  #googleplus = "Your Google+ account URL" # https://plus.google.com/u/0/xxxxxx
  github = "jeqo"
  #gitlab = "Your GitLab username"
  #youtube = "Your YouTube username"
  linkedin = "jeqo89"
  # Disqus shortname
  disqus = "jeqoblog"
  # Google Analytics API key.
  ga_api_key = "UA-49047812-3"
  author = "Jorge Quilcate Otoya"
  authorwebsite = "jeqo.github.com"
  avatar = "/images/jeqo.jpg"
  contact = "mailto:quilcate.jorge@gmail.com"
  bio = "peruvian, husband, software engineer"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "back-end, integration, devops"
  # Logo image. This is displayed ogp image.
  # logo = "/path/to/logo"
  favicon = "/images/favicon.ico"

[Languages]
[Languages.en]
    weight = 1

[[Languages.en.menu.main]]
    name = "Posts"
    pre = ""
    weight = -100
    url = "/posts"

[[Languages.en.menu.main]]
    name = "Talks"
    pre = ""
    weight = -90
    url = "/talks"

[[Languages.en.menu.main]]
    name = "Notes"
    pre = ""
    weight = -80
    url = "/notes"

[[Languages.en.menu.main]]
    name = "About"
    pre = ""
    weight = -70
    url = "/about"

[Languages.es]
    url = "/es"
    weight = 2

[[Languages.es.menu.main]]
    name = "Posts"
    pre = ""
    weight = -100
    url = "/posts"

[[Languages.es.menu.main]]
    name = "Presentaciones"
    pre = ""
    weight = -90
    url = "/talks"

[[Languages.es.menu.main]]
    name = "Notas"
    pre = ""
    weight = -80
    url = "/notes"

[[Languages.es.menu.main]]
    name = "Acerca"
    pre = ""
    weight = -70
    url = "/about"

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
