languageCode = "en-us"
title = "@jeqo"
baseurl = "https://jeqo.github.io/"

theme = "jeqo-theme"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

MetaDataFormat = "yaml"
PygmentsStyle = "default"

disqusShortname = "jeqoblog"
googleAnalytics = "UA-49047812-3"

[author]
    name = "Jorge Quilcate Otoya"

[params]
    description = "back-end, integration, devops, etc."

[taxonomies]
    tag = "tags"
    category = "categories"

[Languages]
[Languages.en]
    weight = 1

[[Languages.en.menu.top]]
    name = "Blog"
    pre = ""
    weight = -100
    url = "/post/"

[[Languages.en.menu.top]]
    name = "Talks"
    pre = ""
    weight = -90
    url = "/talk/"

[[Languages.en.menu.top]]
    name = "Notes"
    pre = ""
    weight = -80
    url = "/note/"

[[Languages.en.menu.main]]
    name = "GitHub"
    pre = ""
    weight = -100
    url = "https://github.com/jeqo/"
[[Languages.en.menu.main]]
    name = "Twitter"
    pre = ""
    weight = -90
    url = "https://twitter.com/jeqo89"
[[Languages.en.menu.main]]
    name = "RSS"
    pre = ""
    weight = -80
    url = "index.xml"

[Languages.es]
    url = "/es/"
    weight = 2
    description = "back-end, integration, devops, etc."

[[Languages.es.menu.top]]
    name = "Blog"
    pre = ""
    weight = -100
    url = "/post/"

[[Languages.es.menu.top]]
    name = "Presentaciones"
    pre = ""
    weight = -90
    url = "/talk/"

[[Languages.es.menu.top]]
    name = "Notas"
    pre = ""
    weight = -80
    url = "/note/"

[[Languages.es.menu.main]]
    name = "GitHub"
    pre = ""
    weight = -100
    url = "https://github.com/jeqo"
[[Languages.es.menu.main]]
    name = "Twitter"
    pre = ""
    weight = -90
    url = "https://twitter.com/jeqo89"
[[Languages.es.menu.main]]
    name = "RSS"
    pre = ""
    weight = -80
    url = "index.xml"
